# 텐서 연산

keras.layers.Dense(512, activation='relu')
==> output = relu(dot(W, input) + b)

## 행렬곱



In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([[1,2,3]])
w = tf.constant([[5],[5],[5]])
y = tf.matmul(x, w)
#x.shape()
print(x.get_shape())

(1, 3)


In [3]:
result = y
print(result)

tf.Tensor([[30]], shape=(1, 1), dtype=int32)


# 텐서 크기 변환

In [4]:
import numpy as np
x = np.array([[0.,1.], [1.,2.], [2.,3.]])


In [5]:
print(x.shape)

(3, 2)


In [6]:
x = x.reshape((6,1))

In [7]:
x

array([[0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [3.]])

In [8]:
x = x.reshape((2,3))

In [9]:
x

array([[0., 1., 1.],
       [2., 2., 3.]])

In [10]:
x = np.transpose(x)

In [11]:
x

array([[0., 2.],
       [1., 2.],
       [1., 3.]])