# 선형회귀

To learn:
* 선형회귀
* flatten

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [20]:
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [21]:
seed

0

In [22]:
df = pd.read_csv("c:/temp/housing1.csv", delim_whitespace=True, header=None)

In [23]:
df

0     1      2   3      4      5      6       7   8      9     10  \
0     0.00632  18.0   2.31   0  0.538  6.575   65.2  4.0900   1  296.0  15.3   
1     0.02731   0.0   7.07   0  0.469  6.421   78.9  4.9671   2  242.0  17.8   
2     0.02729   0.0   7.07   0  0.469  7.185   61.1  4.9671   2  242.0  17.8   
3     0.03237   0.0   2.18   0  0.458  6.998   45.8  6.0622   3  222.0  18.7   
4     0.06905   0.0   2.18   0  0.458  7.147   54.2  6.0622   3  222.0  18.7   
5     0.02985   0.0   2.18   0  0.458  6.430   58.7  6.0622   3  222.0  18.7   
6     0.08829  12.5   7.87   0  0.524  6.012   66.6  5.5605   5  311.0  15.2   
7     0.14455  12.5   7.87   0  0.524  6.172   96.1  5.9505   5  311.0  15.2   
8     0.21124  12.5   7.87   0  0.524  5.631  100.0  6.0821   5  311.0  15.2   
9     0.17004  12.5   7.87   0  0.524  6.004   85.9  6.5921   5  311.0  15.2   
10    0.22489  12.5   7.87   0  0.524  6.377   94.3  6.3467   5  311.0  15.2   
11    0.11747  12.5   7.87   0  0.524  6.009   82.9  6.2267   5  311.0  15.2   
12    0.09378  12.5   7.87   0  0.524  5.889   39.0  5.4509   5  311.0  15.2   
13    0.62976   0.0   8.14   0  0.538  5.949   61.8  4.7075   4  307.0  21.0   
14    0.63796   0.0   8.14   0  0.538  6.096   84.5  4.4619   4  307.0  21.0   
15    0.62739   0.0   8.14   0  0.538  5.834   56.5  4.4986   4  307.0  21.0   
16    1.05393   0.0   8.14   0  0.538  5.935   29.3  4.4986   4  307.0  21.0   
17    0.78420   0.0   8.14   0  0.538  5.990   81.7  4.2579   4  307.0  21.0   
18    0.80271   0.0   8.14   0  0.538  5.456   36.6  3.7965   4  307.0  21.0   
19    0.72580   0.0   8.14   0  0.538  5.727   69.5  3.7965   4  307.0  21.0   
20    1.25179   0.0   8.14   0  0.538  5.570   98.1  3.7979   4  307.0  21.0   
21    0.85204   0.0   8.14   0  0.538  5.965   89.2  4.0123   4  307.0  21.0   
22    1.23247   0.0   8.14   0  0.538  6.142   91.7  3.9769   4  307.0  21.0   
23    0.98843   0.0   8.14   0  0.538  5.813  100.0  4.0952   4  307.0  21.0   
24    0.75026   0.0   8.14   0  0.538  5.924   94.1  4.3996   4  307.0  21.0   
25    0.84054   0.0   8.14   0  0.538  5.599   85.7  4.4546   4  307.0  21.0   
26    0.67191   0.0   8.14   0  0.538  5.813   90.3  4.6820   4  307.0  21.0   
27    0.95577   0.0   8.14   0  0.538  6.047   88.8  4.4534   4  307.0  21.0   
28    0.77299   0.0   8.14   0  0.538  6.495   94.4  4.4547   4  307.0  21.0   
29    1.00245   0.0   8.14   0  0.538  6.674   87.3  4.2390   4  307.0  21.0   
..        ...   ...    ...  ..    ...    ...    ...     ...  ..    ...   ...   
476   4.87141   0.0  18.10   0  0.614  6.484   93.6  2.3053  24  666.0  20.2   
477  15.02340   0.0  18.10   0  0.614  5.304   97.3  2.1007  24  666.0  20.2   
478  10.23300   0.0  18.10   0  0.614  6.185   96.7  2.1705  24  666.0  20.2   
479  14.33370   0.0  18.10   0  0.614  6.229   88.0  1.9512  24  666.0  20.2   
480   5.82401   0.0  18.10   0  0.532  6.242   64.7  3.4242  24  666.0  20.2   
481   5.70818   0.0  18.10   0  0.532  6.750   74.9  3.3317  24  666.0  20.2   
482   5.73116   0.0  18.10   0  0.532  7.061   77.0  3.4106  24  666.0  20.2   
483   2.81838   0.0  18.10   0  0.532  5.762   40.3  4.0983  24  666.0  20.2   
484   2.37857   0.0  18.10   0  0.583  5.871   41.9  3.7240  24  666.0  20.2   
485   3.67367   0.0  18.10   0  0.583  6.312   51.9  3.9917  24  666.0  20.2   
486   5.69175   0.0  18.10   0  0.583  6.114   79.8  3.5459  24  666.0  20.2   
487   4.83567   0.0  18.10   0  0.583  5.905   53.2  3.1523  24  666.0  20.2   
488   0.15086   0.0  27.74   0  0.609  5.454   92.7  1.8209   4  711.0  20.1   
489   0.18337   0.0  27.74   0  0.609  5.414   98.3  1.7554   4  711.0  20.1   
490   0.20746   0.0  27.74   0  0.609  5.093   98.0  1.8226   4  711.0  20.1   
491   0.10574   0.0  27.74   0  0.609  5.983   98.8  1.8681   4  711.0  20.1   
492   0.11132   0.0  27.74   0  0.609  5.983   83.5  2.1099   4  711.0  20.1   
493   0.17331   0.0   9.69   0  0.585  5.707   54.0  2.3817   6  391.0  19.2   
494   0.279

In [24]:
dataset = df.values

In [25]:
x = dataset[:, 0:13]
y = dataset[:, 13]

In [26]:
type(x)

numpy.ndarray

In [27]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [28]:
seed

0

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)

In [30]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(30, input_dim=13, activation='relu'),
  tf.keras.layers.Dense(6, activation='relu'),    
  tf.keras.layers.Dense(1)  # 출력층에 활성함수가 없다!!!
])

In [31]:
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['accuracy'])

In [32]:
history = model.fit(x, y, epochs=200, batch_size=10)

Train on 506 samples
Epoch 1/200
506/506 [==============================] - 1s 2ms/sample - loss: 6190.4939 - accuracy: 0.0000e+00
Epoch 2/200
506/506 [==============================] - 0s 209us/sample - loss: 533.8100 - accuracy: 0.0000e+00
Epoch 3/200
506/506 [==============================] - 0s 259us/sample - loss: 358.6429 - accuracy: 0.0000e+00
Epoch 4/200
506/506 [==============================] - 0s 291us/sample - loss: 199.1332 - accuracy: 0.0000e+00
Epoch 5/200
506/506 [==============================] - 0s 281us/sample - loss: 133.7271 - accuracy: 0.0000e+00
Epoch 6/200
506/506 [==============================] - 0s 269us/sample - loss: 110.4228 - accuracy: 0.0000e+00
Epoch 7/200
506/506 [==============================] - 0s 261us/sample - loss: 84.1116 - accuracy: 0.0000e+00
Epoch 8/200
506/506 [==============================] - 0s 267us/sample - loss: 74.6296 - accuracy: 0.0000e+00
Epoch 9/200
506/506 [==============================] - 0s 259us/sample - loss: 72.1954 - accur

506/506 [==============================] - 0s 200us/sample - loss: 27.4479 - accuracy: 0.0000e+00
Epoch 75/200
506/506 [==============================] - 0s 182us/sample - loss: 27.6997 - accuracy: 0.0000e+00
Epoch 76/200
506/506 [==============================] - 0s 233us/sample - loss: 27.8386 - accuracy: 0.0000e+00
Epoch 77/200
506/506 [==============================] - 0s 257us/sample - loss: 27.0126 - accuracy: 0.0000e+00
Epoch 78/200
506/506 [==============================] - 0s 318us/sample - loss: 27.3569 - accuracy: 0.0000e+00
Epoch 79/200
506/506 [==============================] - 0s 289us/sample - loss: 28.2239 - accuracy: 0.0000e+00
Epoch 80/200
506/506 [==============================] - 0s 279us/sample - loss: 27.0437 - accuracy: 0.0000e+00
Epoch 81/200
506/506 [==============================] - 0s 249us/sample - loss: 27.0670 - accuracy: 0.0000e+00
Epoch 82/200
506/506 [==============================] - 0s 415us/sample - loss: 27.8896 - accuracy: 0.0000e+00
Epoch 83/200
5

506/506 [==============================] - 0s 462us/sample - loss: 20.3632 - accuracy: 0.0000e+00
Epoch 147/200
506/506 [==============================] - 0s 447us/sample - loss: 19.6412 - accuracy: 0.0000e+00
Epoch 148/200
506/506 [==============================] - 0s 362us/sample - loss: 19.8564 - accuracy: 0.0000e+00
Epoch 149/200
506/506 [==============================] - 0s 342us/sample - loss: 20.4787 - accuracy: 0.0000e+00
Epoch 150/200
506/506 [==============================] - 0s 283us/sample - loss: 19.3011 - accuracy: 0.0000e+00
Epoch 151/200
506/506 [==============================] - 0s 302us/sample - loss: 18.4849 - accuracy: 0.0000e+00
Epoch 152/200
506/506 [==============================] - 0s 300us/sample - loss: 18.4153 - accuracy: 0.0000e+00
Epoch 153/200
506/506 [==============================] - 0s 429us/sample - loss: 19.1933 - accuracy: 0.0000e+00
Epoch 154/200
506/506 [==============================] - 0s 279us/sample - loss: 18.0573 - accuracy: 0.0000e+00
Epoch 

In [33]:
# 예측값과 실제값의 비교
y_prediction = model.predict(x_test).flatten()

In [34]:
for i in range(10):
    label = y_test[i]
    prediction = y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(label,prediction))

실제가격: 22.600, 예상가격: 22.718
실제가격: 50.000, 예상가격: 32.755
실제가격: 23.000, 예상가격: 24.473
실제가격: 8.300, 예상가격: 11.616
실제가격: 21.200, 예상가격: 19.422
실제가격: 19.900, 예상가격: 21.562
실제가격: 20.600, 예상가격: 24.425
실제가격: 18.700, 예상가격: 22.596
실제가격: 16.100, 예상가격: 17.661
실제가격: 18.600, 예상가격: 17.261


In [35]:
y_prediction_not_flatten = model.predict(x_test)

In [36]:
y_prediction.shape

(152,)

In [37]:
y_prediction_not_flatten.shape

(152, 1)

In [38]:
y_prediction

array([22.71759  , 32.75496  , 24.473112 , 11.61566  , 19.421797 ,
       21.562368 , 24.424679 , 22.596016 , 17.660803 , 17.26089  ,
        7.16895  , 17.24829  , 19.377466 , 10.885748 , 49.996304 ,
       32.77073  , 27.731651 , 35.96945  , 32.326836 , 22.295818 ,
       24.607235 , 22.563026 , 18.68688  , 26.55762  , 22.398968 ,
       22.551176 , 19.6509   , 15.13994  , 39.89024  , 18.209349 ,
       16.339088 , 22.397436 , 19.77376  , 21.085392 , 27.463148 ,
       24.235844 , 10.981678 , 34.65657  , 18.0451   , 13.519016 ,
       25.210032 , 21.537256 , 19.001255 , 15.552217 , 24.545834 ,
       21.986818 , 20.510147 , 20.589798 , 15.702234 , 24.388607 ,
       18.06291  , 18.919352 , 19.903143 , 34.6011   ,  9.820245 ,
       20.449982 , 21.436367 , 18.246359 , 20.724869 , 19.722197 ,
       23.098976 , 20.851206 , 34.23397  , 34.13142  , 17.159449 ,
       35.98131  , 18.324423 , 18.906889 , 19.595737 , 22.2631   ,
       19.173077 , 24.907934 , 33.178143 , 33.293648 , 35.2623

In [39]:
y_prediction_not_flatten

array([[22.71759  ],
       [32.75496  ],
       [24.473112 ],
       [11.61566  ],
       [19.421797 ],
       [21.562368 ],
       [24.424679 ],
       [22.596016 ],
       [17.660803 ],
       [17.26089  ],
       [ 7.16895  ],
       [17.24829  ],
       [19.377466 ],
       [10.885748 ],
       [49.996304 ],
       [32.77073  ],
       [27.731651 ],
       [35.96945  ],
       [32.326836 ],
       [22.295818 ],
       [24.607235 ],
       [22.563026 ],
       [18.68688  ],
       [26.55762  ],
       [22.398968 ],
       [22.551176 ],
       [19.6509   ],
       [15.13994  ],
       [39.89024  ],
       [18.209349 ],
       [16.339088 ],
       [22.397436 ],
       [19.77376  ],
       [21.085392 ],
       [27.463148 ],
       [24.235844 ],
       [10.981678 ],
       [34.65657  ],
       [18.0451   ],
       [13.519016 ],
       [25.210032 ],
       [21.537256 ],
       [19.001255 ],
       [15.552217 ],
       [24.545834 ],
       [21.986818 ],
       [20.510147 ],
       [20.58

In [40]:
weights = model.get_weights()

In [41]:
weights

[array([[-3.29988211e-01, -2.19220489e-01,  2.64399648e-02,
          4.57646847e-02, -3.97825986e-01,  3.57061356e-01,
         -2.55519114e-02,  3.54447186e-01, -7.43716717e-01,
         -3.55438620e-01,  1.56751394e-01, -8.78480151e-02,
          5.39819598e-02,  7.56877149e-03, -1.12200171e-01,
          9.71639156e-02,  3.09154451e-01,  5.27502418e-01,
          3.51741195e-01, -3.10819685e-01, -1.64538965e-01,
         -3.61946493e-01, -1.83049724e-01,  3.04188699e-01,
          4.35526550e-01, -2.60308117e-01,  1.91638410e-01,
         -6.95971310e-01, -4.07265782e-01, -4.49326843e-01],
        [-2.44512126e-01, -1.40500844e-01, -1.55861959e-01,
         -2.98452139e-01, -9.87295508e-02,  1.46554545e-01,
          2.42207758e-02,  3.17686141e-01,  3.33617449e-01,
         -2.63838172e-01, -3.00653696e-01,  1.50295004e-01,
         -2.40620568e-01,  3.65044214e-02,  2.90326029e-01,
         -2.42221072e-01, -3.39452863e-01, -4.95758392e-02,
          7.08899945e-02,  2.27917194e-

In [42]:
weights1 = model.layers[0].get_weights()[0]
biases1 = model.layers[0].get_weights()[1]

In [43]:
weights1

array([[-3.29988211e-01, -2.19220489e-01,  2.64399648e-02,
         4.57646847e-02, -3.97825986e-01,  3.57061356e-01,
        -2.55519114e-02,  3.54447186e-01, -7.43716717e-01,
        -3.55438620e-01,  1.56751394e-01, -8.78480151e-02,
         5.39819598e-02,  7.56877149e-03, -1.12200171e-01,
         9.71639156e-02,  3.09154451e-01,  5.27502418e-01,
         3.51741195e-01, -3.10819685e-01, -1.64538965e-01,
        -3.61946493e-01, -1.83049724e-01,  3.04188699e-01,
         4.35526550e-01, -2.60308117e-01,  1.91638410e-01,
        -6.95971310e-01, -4.07265782e-01, -4.49326843e-01],
       [-2.44512126e-01, -1.40500844e-01, -1.55861959e-01,
        -2.98452139e-01, -9.87295508e-02,  1.46554545e-01,
         2.42207758e-02,  3.17686141e-01,  3.33617449e-01,
        -2.63838172e-01, -3.00653696e-01,  1.50295004e-01,
        -2.40620568e-01,  3.65044214e-02,  2.90326029e-01,
        -2.42221072e-01, -3.39452863e-01, -4.95758392e-02,
         7.08899945e-02,  2.27917194e-01,  6.27005696e-